### ISSUE TITLE
Not possible to anonymize and hide

### ISSUE THREAD

**Issue by lbjay** [davidsev/owlbear-token-anonymizer#1]
First off, great extension. Very much something I needed. My issue is that I don't seem to be able to both **hide** and **anonymize** a token. If I have a token set to hide and then toggle it to anonymized, the token also toggles back to shown (although the show/hide token setting in the UI doesn't also update). I will sometimes keep monster tokens hidden until the PCs trigger something and it would be much easier if I could hide/show them without this interfering with the anonymized setting. Thanks!

**Comment by davidsev** [comment]
Hi,
When a token is anonymized I make a "fake" token for the players to see, and hide the orginal.  So hiding and anonymizing don't play well together.

What you should be able to do is just hide the token without clicking anonymize, and then when you want it visible don't press unhide, instead click the anonymize button which will "unhide" it.

**Comment by lbjay** [comment]
Ahh, I see. Thanks for the workaround. I feel dumb that didn't occur to me. :laughing:
