### ISSUE TITLE
Token is completely hidden from view

### ISSUE THREAD

**Issue by Daniebear** [davidsev/owlbear-token-anonymizer#2]
Hey,

I'm using this extension on owlbear rodeo and before the 2.1 update only the token names would be hidden, but now the entire token is hidden when I anonymize the token. Which hides the entire toke from the view of my players. I added an image so you can see what I mean. 

Hopefully you are able to fix this.
![Screenshot_1](https://github.com/davidsev/owlbear-token-anonymizer/assets/147020197/6f4c340a-690b-4add-a3c7-ac15f8c1a38a)

**Comment by davidsev** [comment]
Hi,

I've not been able to replicate this, but I've updated the extension to use the newest SDK so hopefully that'll fix it.  You might need to delete and re-create the token.

If it's still not working can you export the scene and send me a copy?

**Comment by Daniebear** [comment]
Hey,

I did what you said and that did seem to fix it. Thanks for the advice. I will update all the tokens so it will work from now on. Thanks again!
